name: analytics-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - imageio
  - imageio-ffmpeg
  - opencv
  - pygame
  - jupyterlab
  - scikit-learn
  - pip:
      - stable-baselines3
      - gymnasium
      - moviepy
      - wandb
      - tqdm
      - pyquaternion
